name: Publish to crates.io

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Crates.io Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the wrapper repo 🛒
        uses: actions/checkout@v4

      - name: Set up Rust 🦀
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo 🧳
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Publish crate 📦✨
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: cargo publish --locked
